model_type: "IncrFeatStridedConvFCUpsampReflectPadAE"
latent_dims: 32

max_implausible:
max_plausible:
viz: False
no_threshold:
thresholds_file:
valid_bundle_path_test:
invalid_bundle_file_test:

streamline_length: 256

device: "cuda"