name: label pull request on paths
# See https://github.com/actions/labeler

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # File with label/regex match dictionary
        configuration-path: .github/labels.yml
