name: label pull request on title

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install packages
      run: |
        python -m pip install --upgrade --user pip
        pip install ghapi==1.0.1
        pip install pyyaml
        pip --version
        pip list
    - name: Label pull request
      run: python .github/scripts/pr_title_regex_labeler.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
